import type { Metadata } from "next";
import { apercuRegular } from "@/app/fonts/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${apercuRegular.className} flex flex-col w-screen min-h-screen bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
